In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [2]:
descriptors = pd.read_csv('train_descriptors.csv')
descriptors

identifiers  Unnamed: 0                          name        ABC  \
0          COXSUE       11365   Optimised_Molecules_V3.3460   8.773011   
1          TUWFAU       58476  Optimised_Molecules_V3.19496  10.813451   
2          DUTHEG       31879   Optimised_Molecules_V3.5074  10.922841   
3        AXUDED08        2885    Optimised_Molecules_V3.988   7.140017   
4          ARAGUV        2660    Optimised_Molecules_V3.795   7.399237   
...           ...         ...                           ...        ...   
13444    GICQAN01       34720   Optimised_Molecules_V3.7209  11.589507   
13445      UNDECO       58781  Optimised_Molecules_V3.19870   8.594671   
13446      IHECIH       38371   Optimised_Molecules_V3.9058   8.065904   
13447    MQUCXA11       45201  Optimised_Molecules_V3.12909  10.813451   
13448      CAZFUF        7655   Optimised_Molecules_V3.2645  10.187224   

           ABCGG  nAcid  nBase    SpAbs_A   SpMax_A  SpDiam_A  ...  \
0       8.632564      0      0  14.599164  2.244739  4.388162  ...   
1      10.346393      0      0  18.488707  2.357869  4.715737  ...   
2       9.584172      0      0  16.685332  2.436274  4.872549  ...   
3       6.873356      0      0  12.857279  2.214320  4.428639  ...   
4       7.308033      0      0  11.638727  2.249778  4.311276  ...   
...          ...    ...    ...        ...       ...       ...  ...   
13444  11.335446      0      0  18.593111  2.444247  4.716186  ...   
13445   6.996374      0      0  15.070075  2.071027  4.107492  ...   
13446   7.608752      1      0  13.246202  2.248763  4.497527  ...   
13447   9.387164      0      0  17.683997  2.402187  4.804373  ...   
13448   9.217325      0      0  17.004191  2.270288  4.540576  ...   

               MW        AMW  WPath  WPol  Zagreb1  Zagreb2  mZagreb1  \
0      185.062283   8.046186    219    11     54.0     58.0  4.833333   
1      199.110947   7.111105    364    22     70.0     80.0  6.805556   
2      191.080710   8.307857    271    22     74.0     87.0  5.666667   
3      136.052429   7.558468    121    11     44.0     48.0  3.722222   
4      139.074562   7.319714    125     8     46.0     49.0  4.333333   
...           ...        ...    ...   ...      ...      ...       ...   
13444  214.008667  12.588745    344    20     78.0     92.0  5.916667   
13445  168.151415   5.254732    206    13     50.0     51.0  3.611111   
13446  153.042593   8.502366    158    12     50.0     54.0  4.583333   
13447  186.079313   7.753305    283    21     72.0     84.0  5.055556   
13448  212.025563   9.637526    338    17     64.0     70.0  5.944444   

       mZagreb2                     InchiKey  \
0      2.777778  UYSCRWBEPUAZRA-UHFFFAOYSA-N   
1      3.583333  RYPSYCXCJSHDJX-UHFFFAOYSA-N   
2      3.000000  PVRUUABKIQNQFL-UHFFFAOYSA-N   
3      2.444444  QPJVMBTYPHYUOC-UHFFFAOYSA-N   
4      2.250000  LUFRABHJXNJTNZ-UHFFFAOYSA-N   
...         ...                          ...   
13444  3.277778  AMGTUMYRSHDKFL-UHFFFAOYSA-N   
13445  2.916667  UPOSSYJVWXLPTA-UHFFFAOYSA-N   
13446  2.527778  VMONVJKJUDZYIE-UHFFFAOYSA-N   
13447  3.083333  AMOPWISLTWLTGM-UHFFFAOYSA-N   
13448  3.277778  WBZIRDVHGBWLDE-UHFFFAOYSA-N   

                                        SMILES  
0                        CC(=O)NN=C(C)C1=NCCS1  
1                    CC(C)N(C)c1ccc(C#N)cc1C#N  
2                    Cc1cc(=O)n2c(N)nc(C)nc2n1  
3                              COC(=O)c1ccccc1  
4                         CC(=O)Nc1cc(C)[nH]n1  
...                                        ...  
13444  Nc1nc(-c2c([N+](=O)[O-])no[n+]2[O-])no1  
13445                          O=C1CCCCCCCCCC1  
13446                        O=C(O)Cn1ccccc1=O  
13447                  Cc1cc(C(N)=O)nc2ccccc12  
13448           COC(=S)Nc1ccc([N+](=O)[O-])cc1  

[13449 rows x 1618 columns]

In [3]:
train_crystals=np.loadtxt('train_crystals2.csv',delimiter=',', skiprows=1)
print(train_crystals)

[[4.73620000e+00 1.70760000e+01 1.14150000e+01 ... 9.20431558e+02
  1.33680186e+00 6.67769313e-01]
 [8.98320000e+00 1.26212000e+01 9.68630000e+00 ... 1.09724612e+03
  1.20616269e+00 6.89271542e-01]
 [1.11369000e+01 1.89130000e+01 4.03110000e+00 ... 8.49079420e+02
  1.49563269e+00 7.29063731e-01]
 ...
 [7.45020000e+00 1.00060000e+01 9.96000000e+00 ... 6.97884928e+02
  1.45747102e+00 7.12136223e-01]
 [7.72390000e+00 1.03039000e+01 1.16239000e+01 ... 9.22703141e+02
  1.34044449e+00 7.08705245e-01]
 [7.33400000e+00 7.66040000e+00 1.61964000e+01 ... 9.05543506e+02
  1.55667174e+00 7.30439842e-01]]


In [4]:
y = pd.read_csv('train_crystals2.csv')

In [5]:
descriptor_list = []
for descriptor in descriptors.columns:
    if descriptor != 'identifiers' and descriptor != 'SMILES' and descriptor != 'name':
        try:
            corr = descriptors[descriptor].corr(y['calculated_density'])
            if abs(corr) > 0.7:
                print(f"{descriptor}: {corr}")
                descriptor_list.append(descriptor)
        except:
            pass
del descriptor_list[14]
del descriptor_list[16]

ATS0Z: 0.7768800836325678
ATS0m: 0.7712942779159075
AATS0Z: 0.8044806860276815
AATS1Z: 0.7506644259234482
AATS0m: 0.7832240683090961
AATS1m: 0.764534031810706
AATS0v: 0.7284572889659848
AATSC0Z: 0.7809608699592755
AATSC0m: 0.7695506107993237
MZ: 0.8877814417096513
Mm: 0.8889703675407987
Mv: 0.7231352753916281
MAXssSiH2: -0.9204918719794177
MAXsssSiH: -0.7806574573848057
MAXssPH: -1.0
MINssSiH2: -0.9204918719794177
MINsssSiH: -0.7806574573848057
MINssPH: -1.0
MIC0: 0.8502951865599613
MIC1: 0.7942077212853146
MIC2: 0.772628255048393
MIC3: 0.776417328663542
MIC4: 0.7751625353829442
MIC5: 0.7749152244189342
AMW: 0.8892465212998912


In [6]:
l = []
for d in descriptor_list:
    l.append(descriptors[d].to_numpy())

In [7]:
density = train_crystals[:,9]

In [8]:
def normalise(x):
    mean = np.nanmean(x)
    x = np.nan_to_num(x, mean)
    x_max = np.amax(x)
    x_min = np.amin(x)
    x_n = (x-x_min)/(x_max-x_min)
    return x_n

In [9]:
for i in range(0, len(l)):
    l[i] = normalise(l[i])

In [10]:
density_n = normalise(density)
density_n = density_n.reshape(-1, 1)

In [11]:
X = np.array([])
for m in range(0,len(l[0])):
    new_array = np.array([])
    for j in range(0,len(descriptor_list)):
        new_array = np.append(new_array,l[j][m])
    X = np.append(X,new_array)
print(X)

[0.03800366 0.02659849 0.00944521 ... 0.23194934 0.23194934 0.05636463]


In [12]:
X = np.reshape(X,(13449,len(descriptor_list)))

In [13]:
m = int(0.8*13449)
X_train = X[:m,:]
X_test = X[m:,:]
Y_train = density_n[:m,:]
Y_test = density_n[m:,:]

In [14]:
X_train

array([[0.03800366, 0.02659849, 0.00944521, ..., 0.19423821, 0.19423821,
        0.04043816],
       [0.03010531, 0.02094196, 0.00472286, ..., 0.17679151, 0.17679151,
        0.03107966],
       [0.03090659, 0.02162059, 0.00704251, ..., 0.20104636, 0.20104636,
        0.04305702],
       ...,
       [0.02403846, 0.01685591, 0.00804098, ..., 0.19497838, 0.19497838,
        0.04823664],
       [0.02323718, 0.01621918, 0.00767396, ..., 0.12502583, 0.12502583,
        0.0399978 ],
       [0.0172848 , 0.01203824, 0.0044116 , ..., 0.12232379, 0.12232379,
        0.03111453]])

In [15]:
linear_regression = LinearRegression()
linear_regression.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
y_pred = linear_regression.predict(X_test)

In [17]:
mean_absolute_error(Y_test, y_pred)

0.012791916764256549

In [18]:
print(y_pred)

[[0.28859609]
 [0.24032154]
 [0.23085065]
 ...
 [0.26239391]
 [0.23837075]
 [0.27776029]]


In [19]:
np.savetxt('task_1_test.csv', y_pred, delimiter=',')

# Validation

In [20]:
test_descriptors = pd.read_csv('test_descriptors.csv')
test_descriptors

identifiers  Unnamed: 0                          name        ABC  \
0       WOKPER02       62533  Optimised_Molecules_V3.21665  11.549067   
1         QAFVAU       52294  Optimised_Molecules_V3.15895  11.629947   
2         YIRLIV       64221  Optimised_Molecules_V3.23019  11.492048   
3         FUWPIW       34287   Optimised_Molecules_V3.6792   9.658457   
4         JODTAX       40419  Optimised_Molecules_V3.10038  10.894331   
...          ...         ...                           ...        ...   
3358      TIYDEM       57993  Optimised_Molecules_V3.19137   8.299214   
3359      IZUTIH       40009   Optimised_Molecules_V3.9600  12.037394   
3360      NIPQUA       48110  Optimised_Molecules_V3.13745   4.352030   
3361      NUQDIO       48637  Optimised_Molecules_V3.14086  10.784941   
3362    PUZHIB02       51929  Optimised_Molecules_V3.15792   8.898979   

          ABCGG  nAcid  nBase    SpAbs_A   SpMax_A  SpDiam_A  ...          MW  \
0     10.258331      0      0  18.481449  2.448488  4.896977  ...  204.042259   
1     10.600629      1      0  18.188997  2.452357  4.790463  ...  242.985384   
2     10.321229      0      2  19.145390  2.298181  4.575893  ...  267.984740   
3      9.148596      0      0  14.911280  2.342923  4.685846  ...  236.951497   
4      9.805274      0      0  18.338436  2.285262  4.570525  ...  245.037419   
...         ...    ...    ...        ...       ...       ...  ...         ...   
3358   9.157523      0      2  13.267203  2.389655  4.779311  ...  303.844279   
3359  10.307385      0      0  19.829524  2.512598  4.931109  ...  234.976170   
3360   4.798324      0      0   7.878462  1.969616  3.939231  ...  103.063329   
3361   9.263360      0      0  17.809610  2.334414  4.668828  ...  223.990804   
3362   8.883053      0      0  14.601126  2.414214  4.828427  ...  353.825437   

            AMW  WPath  WPol  Zagreb1  Zagreb2  mZagreb1  mZagreb2  \
0      8.871403    330    25     78.0     93.0  5.916667  3.305556   
1     11.044790    350    21     78.0     91.0  5.916667  3.250000   
2     11.166031    387    17     74.0     83.0  4.694444  3.361111   
3     12.471131    242    17     62.0     69.0  6.305556  2.888889   
4      8.751336    416    18     68.0     74.0  6.194444  3.527778   
...         ...    ...   ...      ...      ...       ...       ...   
3358  21.703163    183    20     54.0     63.0  7.645833  2.833333   
3359  11.748809    320    25     84.0    103.0  4.416667  3.222222   
3360   6.441458     50     5     24.0     23.0  3.861111  1.916667   
3361  11.199540    298    18     70.0     79.0  4.444444  3.111111   
3362  16.848830    174    21     60.0     72.0  6.666667  2.666667   

                         InchiKey                                   SMILES  
0     UTZHUXAPJIBIBQ-UHFFFAOYSA-N                CC(=O)c1c(O)c2ccccc2oc1=O  
1     NVVJEABWJDEWOA-UHFFFAOYSA-N          O=C(O)Cc1c[nH]c2c(Cl)cc(Cl)cc12  
2     VSDAMKFZVPCLKY-UHFFFAOYSA-N               O=C(N=C1NCCO1)c1cccc(Br)c1  
3     UYAFIBWBOORJHP-UHFFFAOYSA-N                CC(=O)Nc1c(Cl)cc(Cl)cc1Cl  
4     BMSSRNRFXGWOEZ-UHFFFAOYSA-N               CCCCC(=O)Nc1ccc(Cl)c(Cl)c1  
...                           ...                                      ...  
3358  YVCMOXJVRGTHCI-UHFFFAOYSA-N  NC(=NBr)C(Br)([N+](=O)[O-])[N+](=O)[O-]  
3359  JPDVVLJFKMAGTR-UHFFFAOYSA-N           O=[N+]([O-])c1ccc2cccc3c2c1SS3  
3360  QWKAVVNRCKPKNM-UHFFFAOYSA-N                               CCOC(C)=NO  
3361  NRFQZTCQAYEXEE-UHFFFAOYSA-N                Clc1cc(Cl)nc(-c2ccccc2)n1  
3362  LTSSSVHTLGQZAQ-UHFFFAOYSA-N                Cc1c(Br)c(C)c(Br)c(C)c1Br  

[3363 rows x 1618 columns]

In [21]:
test_l = []
for d in descriptor_list:
    test_l.append(test_descriptors[d].to_numpy())

In [22]:
for i in range(0, len(test_l)):
    test_l[i] = normalise(test_l[i])

In [23]:
len(test_l[0])

3363

In [24]:
len(descriptor_list)

23

In [28]:
X_validation = np.array([])
for m in range(0,len(test_l[0])):
    new_array = np.array([])
    for j in range(0,len(descriptor_list)):
        new_array = np.append(new_array,test_l[j][m])
    X_validation = np.append(X_validation,new_array)
print(X_validation)

[0.03412532 0.02377915 0.00882836 ... 0.2906506  0.2906506  0.13303595]


In [29]:
X_validation = X_validation.reshape(3363,len(descriptor_list))
X_validation

array([[0.03412532, 0.02377915, 0.00882836, ..., 0.24691859, 0.24691859,
        0.0519783 ],
       [0.06102958, 0.04473993, 0.01922181, ..., 0.30522762, 0.30522762,
        0.07406182],
       [0.10167715, 0.08630102, 0.03079372, ..., 0.31670778, 0.31670778,
        0.07529373],
       ...,
       [0.01490799, 0.01025142, 0.00506757, ..., 0.15486099, 0.15486099,
        0.02728794],
       [0.05637084, 0.04150494, 0.01973439, ..., 0.30062554, 0.30062554,
        0.07563422],
       [0.22909387, 0.20600335, 0.08439289, ..., 0.2906506 , 0.2906506 ,
        0.13303595]])

In [30]:
y_val = linear_regression.predict(X_validation)

In [31]:
y_val.shape

(3363, 1)

In [32]:
np.savetxt('task_1_predictions.csv', y_val, delimiter=',')